// {
//           vendor: "ninja",
//           cardColor: "#222222",
//           cardIcon: "ninja.svg",
//           cardNumber: "5768 9067 8903 7291",
//           name: "Lorena Morgan",
//           validMonth: 11,
//           validYear: 22,
//         },
//         {
//           vendor: "bitcoin",
//           cardColor: "#FFAE34",
//           cardIcon: "bitcoin.svg",
//           cardNumber: "3456 7891 5467 3425",
//           name: "Kimberly Park",
//           validMonth: 12,
//           validYear: 24,
//         },
//         {
//           vendor: "blockchain",
//           cardColor: "#8B58F9",
//           cardIcon: "blockchain.svg",
//           cardNumber: "1223 4567 8934 5679",
//           name: "Kayla Gonzales",
//           validMonth: 10,
//           validYear: 23,
//         },